name: Close Related Issue on Merge

on:
  pull_request:
    types: [closed]
    branches: [dev-be, dev-fe]

jobs:
  close-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Close related issue
        if: ${{ github.event.pull_request.merged == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBERS=$(echo "${{ github.event.pull_request.body }}" | grep -o -E '([cC]lose #[0-9]+)' | grep -o '[0-9]\+')

          for ISSUE_NUMBER in $ISSUE_NUMBERS; do
            echo "Closing issue #$ISSUE_NUMBER"
            curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER \
                 -d '{"state": "closed"}'
          done
